# repositories:
#   - name: minio-operator
#     url: https://operator.min.io
releases:
  # - name: minio-operator
  #   chart: minio-operator/operator
  #   namespace: minio-operator
  # - name: minio-tenant
  #   chart: minio-operator/tenant
  #   namespace: minio-tenant
  #   values:
  #     - ./minio-tenant-values.yaml
  #   needs:
  #     - minio-operator
  #   hooks:
  #     - events: ["postsync"]
  #       command: "kubectl"
  #       args:
  #         - "apply"
  #         - "-f"
  #         - "./jobs.yaml"

  # - name: kafka
  #   chart: ./kafka/charts
  
  - name: exam-generation-frontend
    chart: ./frontend/exam-generation-app/charts
    namespace: "exam"

  - name: exam-taking-frontend
    chart: ./frontend/exam-taking-app/charts
    namespace: "exam"

  - name: exam-generation-fn
    chart: ./knative/ExamGenFn/charts
    namespace: "exam"

  - name: exam-taking-fn
    chart: ./knative/ExamTakeFn/charts
    namespace: "exam"

  - name: mongo-trigger-fn
    chart: ./knative/MongoTriggerFn/charts
    namespace: "exam"
  
  - name: email-fn
    chart: ./knative/EmailSendFn/charts
    namespace: "exam"


  - name: post-signup-fn
    chart: ./knative/PostSignUpFn/charts
    namespace: "exam"
  

