apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: kafka-group
  bootstrapServers:
    - kafka-cluster-kafka-bootstrap.strimzi.svc:9092
  topics:
    - email-topic.exams.score
  consumers: 2
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: exam-gen-fn