apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: event-display-source
  namespace: exam
spec:
  consumerGroup: kafka-group
  bootstrapServers:
    - kafka-cluster-kafka-bootstrap.strimzi.svc:909
  topics:
    - exam-generator-topic
  consumers: 2
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      namespace: exam